name: Deploy

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Continuos-Deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.5.0

      - name: Login to Github Container Registry
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io
          # Username used to log against the Docker registry
          username: ${{ github.repository_owner }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.CR_PAT }}
          # Log out from the Docker registry at the end of a job
      #        logout: # optional, default is true

      - name: Short-SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          # List of build-time variables
          # build-args: # optional
          # Build's context is the set of files located in the specified PATH or URL
          context: ./
          # Path to the Dockerfile
          file: ./Dockerfile
          # List of SSH agent socket or keys to expose to the build
          # ssh: # optional
          # List of tags
          tags: |
            ghcr.io/makinarocks/react-recruit:latest
            ghcr.io/makinarocks/react-recruit:${{ steps.short-sha.outputs.sha }}
          # GitHub Token used to authenticate against a repository for Git context
          # github-token: # optional, default is ${{ github.token }}

#      - name: Install yq
#        run: |
#          wget https://github.com/mikefarah/yq/releases/download/v4.4.1/yq_linux_amd64 -O ./yq
#          chmod +x ./yq
#
#      - name: Change image tag on values.yaml
#        run: |
#          cat ./helm/mynode/values.yaml | ./yq e '.image.tag="${{ steps.short-sha.outputs.sha }}"' - | tee ./helm/mynode/values.yaml.tmp
#          mv ./helm/mynode/values.yaml.tmp ./helm/mynode/values.yaml
#
#      - name: Commit file
#        run: |
#          git config --local user.email "seongjinkim1123@gmail.com"
#          git config --local user.name "seongjinkim_ci_cd"
#          git add ./helm/mynode/values.yaml
#          git commit -m "cd : Update image tag in helm values.yaml."
#
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: deployed
#          force: true
